### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by valentinbraem** [lebaston100/OBSmultiviewTally#3]
When I load the background.html file, I have a grey screen.
A idea for fix this ?

![obs64_2017-12-29_15-19-12](https://user-images.githubusercontent.com/34458203/34439084-c83eec1c-ecab-11e7-98ce-b56f0fb659a7.png)

**Comment by lebaston100** [comment]
This is normal. As soon as you setup the sources in the client.js (https://github.com/lebaston100/OBSmultiviewTally#template-configuration) and the websocket plugin is working it will display the red and green "borders"(technically they are the full boxes).
The black boxes shown on the preview picture in the readme are actually where your sources would be and i also removed the small black lines between the boxes.

**Comment by lebaston100** [comment]
If you don't respond in 7 days this will be closed.

**Comment by lebaston100** [comment]
Message added with https://github.com/lebaston100/OBSmultiviewTally/commit/bb44a6adce4ae2b37097881e30a05d2c71e2e5e9
